config/routes.rb
Rails.application.routes.draw do
  root                     'recipes#index'
  post   '/',          to: 'recipes#create'  
  # get    '/recipes/search', to: 'recipes#search'
  get    '/sign_up',   to: 'users#new'
  
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  post   '/follows',   to: 'follows#follow_user'
  delete '/follows',   to: 'follows#unfollow_user'

  resources :users
  resources :recipes do
    resource :like, module: :recipes
    member do
      put 'upvote', to: 'recipes#upvote'
      put 'downvote', to: 'recipes#downvote'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :author, class_name: 'User'
  acts_as_votable

  has_one_attached :photo
  has_many :likes

  has_many :ingredients_recipes, dependent: :destroy
  has_many :ingredients, through: :ingredients_recipes,
                         source: :ingredient

  validates :title, presence: true
  validates :description, presence: true,
                          length: { maximum: 8000 }

  default_scope -> { order(created_at: :desc) }

  def ingredient_tags
    ingredients.map(&:title)
  end

  def ingredient_tags=(tags)
    self.ingredients = tags.split(',').map do |tag|
      Ingredient.find_or_create_by(title: tag)
    end
  end

  def truncated_description
    "#{description.split(' ').first(50).join(' ')}..."
  end
end

app/controllers/recipes/likes_controller.rb
class Recipes::LikesController < ApplicationController
  before_action :authenticate_user
  before_action :set_recipe
  def create
    @recipe.likes.find_or_create_by(user_id: current_user.id)

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.js
    end
  end

  def destroy
    @recipe.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @recipe }
      format.js
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user
  before_action :set_recipe, only: %i[show
                                      update
                                      upvote
                                      downvote
                                      destroy]

  def index
    @user = current_user
    @recipe = Recipe.new
    @people = User.other_users(current_user).includes([:photo_attachment])
    @q = Recipe.ransack(params[:q])
    @timeline = @q.result.includes(author: [:photo_attachment])
      .includes(:ingredients)
      .includes(:ingredients_recipes)
      .includes(ingredients_recipes: [:ingredient])
  end

  def show; end

  def create
    @recipe = @current_user.recipes.create(recipe_params)
    flash[:notice] = 'Empty post is not allowed' unless @recipe.save
    redirect_to :root
  end

  def update
    @recipe.update(recipe_params)
    redirect_to @recipe
  end

  def upvote
    @recipe.liked_by(current_user)
    redirect_to @recipe
  end

  def downvote
    @recipe.downvote_from(current_user)
    if @recipe.get_dislikes.size >= 10
      @recipe.destroy
      flash[:notice] = 'Recipe deleted because of too many downvotes'
    end
    redirect_to @recipe
  end

  def destroy
    @recipe.destroy
    flash[:notice] = 'Successfully deleted recipe'
    redirect_to :root
  end

  private

  def recipe_params
    params.require(:recipe).permit(:description,
                                   :title,
                                   :ingredient_tags,
                                   :photo)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_votes.erb
<div class="flex">
  <div class="mx-2">
    <p>
      <%= link_to downvote_recipe_path, method: :put do %>
        <svg class="w-8 fill-current hover:text-red-600 text-red-400" style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Arrow_up" viewBox="0 0 20 20" xml:space="preserve"><path d="M10 2.5L16.5 9H13v8H7V9H3.5L10 2.5z"/></svg>
        <small class="font-bold text-gray-500"><%= @recipe.get_dislikes.size %></small>
      <% end %>
    </p>
  </div>
  <div class="mx-2">
    <p>
      <%= link_to upvote_recipe_path, method: :put do %>
        <svg class="w-8 fill-current hover:text-green-600 text-green-400" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Arrow_up" viewBox="0 0 20 20" xml:space="preserve"><path d="M10 2.5L16.5 9H13v8H7V9H3.5L10 2.5z"/></svg>
        <small class="font-bold text-gray-500"><%= @recipe.get_likes.size %></small>
      <% end %>
    </p>
  </div>
</div>

app/views/recipes/index.html.erb
<%= provide(:title, 'Home') %>
<div class=" posts-container w-full m-0 flex flex-col">
  <%= render 'shared/search' %>
  <%= render 'shared/new_recipe'%>
  <div class="flex w-4/5 mx-auto flex-col">
    <%= render 'shared/timeline'%>
  </div>
</div>
<%# Who to follow sidebar %>
<div class="flex w-auto justify-between px-12 py-4 bg-gray-200">
  <div class="flex-col items-center right-sidebar">
    <%= render 'shared/who_to_follow'%>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="m-5 shadow-lg text-gray-600 rounded-lg flex-wrap 
              hover:shadow-2xl bg-gray-100 flex content-between p-4">
  <div class="img-and-text justify-between w-full flex">
    <%# left sidebar %>
    <div class="img-box w-2/6">
      <% if @recipe.author.photo.attached? %>
        <%= image_tag(@recipe.author.photo, 
                        class: "rounded-full
                                mx-auto mb-2 
                                h-20 w-20
                                object-cover
                                object-center")%>
      <% end %>
      <span class="font-bold text-gray-900">
        <%= @recipe.author.full_name %>
      </span>
      <% if @recipe.author == current_user %>
        <%= form_with(model: @recipe, class: "flex flex-col mt-10") do |f| %>
          <%= f.label :photo, 
                    'Recipe photo',
                     class: 'bg-gray-600 
                             hover:bg-blue-500 
                             shadow-md p-2 
                             rounded-lg text-white
                             font-bold mb-2'%>
          <%= f.file_field :photo, hidden: true%>
          <%= f.submit 'upload', class: "rounded-lg mb-2 
                                       hover:bg-green-400 
                                       shadow-lg text-sm p-1" %>
        <% end %>
      <% end %>
      <% if @recipe.photo.attached? %>
        <%= image_tag(@recipe.photo)%>
      <% end %>
    </div>
    <%# text block %>
    <div class=" py-4 w-4/6 text-justify flex flex-col">
      <h2 class="font-bold text-2xl mb-4 text-center text-gray-900">
        <%= @recipe.title %>
      </h2>
      <p class="text-2xl mx-auto w-2/3">
        <%= @recipe.description %>
      </p>
    </div>
  </div>
  <%# bottom row with tags, likes and created_at %>
  <div class="bottom w-full">
    <div class="votes items-center justify-between mb-4 w-full flex">
      <div id="votes/delete">
        <% if @recipe.author == current_user %>
          <%= link_to 'Delete recipe', recipe_path, 
                                       method: :delete,
                                       class: "bg-red-500 p-2
                                               rounded-lg uppercase
                                               text-xs font-bold text-gray-800
                                               border-2 border-red-800
                                               hover:bg-red-700" %>
        <% else %>
          <%= render 'votes', locales: @recipe %>
        <% end %>
      </div>
    </div>
    <div class="time-and-tags flex w-full justify-between">
      <small class="text-xs self-end whitespace-no-wrap">
        <%= distance_of_time_in_words_to_now(@recipe.created_at) %>
      </small>
      <ul class="flex items-center flex-wrap">
        <% @recipe.ingredient_tags.each do |tag|%>
          <li class="m-1 rounded-full  px-3 text-xs bg-gray-300 border-gray-400 border-2"><%= tag %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>