config/routes.rb
Rails.application.routes.draw do
  root                     'recipes#index'
  post   '/',          to: 'recipes#create'  
  # get    '/recipes/search', to: 'recipes#search'
  get    '/sign_up',   to: 'users#new'
  
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  post   '/follows',   to: 'follows#follow_user'
  delete '/follows',   to: 'follows#unfollow_user'

  resources :users
  resources :recipes do
    resource :like, module: :recipes
    member do
      put 'upvote', to: 'recipes#upvote'
      put 'downvote', to: 'recipes#downvote'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.full_name = full_name.titleize }
  before_save { self.email = email.downcase }
  acts_as_voter
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  has_one_attached :photo
  has_one_attached :cover_image

  validates :photo, content_type: %i[png jpg jpeg]
  validates :cover_image, content_type: %i[png jpg jpeg]

  has_many :recipes, foreign_key: :author_id, dependent: :destroy

  has_many :outward_follows, class_name: 'Following',
                             foreign_key: :follower_id,
                             dependent: :destroy

  has_many :followed_users, through: :outward_follows,
                            source: :followed

  has_many :inward_follows, class_name: 'Following',
                            foreign_key: :followed_id,
                            dependent: :destroy

  has_many :following_users, through: :inward_follows,
                             source: :follower

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 5, maximum: 20 }
  validates :full_name, presence: true,
                        length: { minimum: 4, maximum: 200 }

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  scope :other_users, ->(user) { where.not(id: user.id) }

  def my_timeline
    followed_user_ids = []
    followed_users.each { |user| followed_user_ids << user.id }
    Recipe.where(author: followed_user_ids + [id])
  end

  def post_count
    recipes.count
  end

  def follow(target_user)
    return if followed?(target_user) || target_user == @current_user

    followed_users << target_user
  end

  def unfollow(target_user)
    followed_users.delete(target_user)
  end

  def followed?(target_user)
    followed_users.include?(target_user)
  end

  def following?(target_user)
    following_users.include?(target_user)
  end

  def follow_count
    followed_users.count
  end

  def follower_count
    following_users.count
  end

  def liked?(recipe)
    recipe.likes.where(user_id: id).any?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: %i[new create]
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @people = @user.following_users.includes(:photo_attachment)
    @timeline = @user.recipes.includes(:author)
      .includes(:ingredients_recipes)
      .includes(:ingredients)
      .includes(ingredients_recipes: [:ingredient])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome #{@user.full_name}"
      log_in @user
      redirect_to :root
    else
      render 'new'
    end
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :email,
                                 :full_name,
                                 :photo,
                                 :cover_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def follow_actions(user)
    return if current_user?(user)

    if current_user.followed?(user)
      render 'shared/unfollow_button'
    else
      render 'shared/follow_button'
    end
  end

  def user_photo_upload(user)
    render 'shared/img_upload' if user == @user
  end

  def follow_status(user)
    'followed' if current_user.followed?(user)
  end
end

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up')%>
<div class="mx-auto">
  <div class="form bg-white shadow-lg rounded-lg mx-auto my-20 text-center items-center justify-center flex flex-col p-4 w-64">
    <%= form_with(model: @user, local: true, class: "flex flex-col") do |f| %>
      <%= render 'shared/errors', object: f.object %>
      <%= f.label :username, hidden: true %>
      <%= f.text_field :username, 
                        autofocus: true,
                        placeholder: 'username',
                        class: "my-3 shadow-lg"%>
      <%= f.label :full_name, hidden: true %>
      <%= f.text_field :full_name, 
                        autofocus: true,
                        placeholder: 'full name',
                        class: "my-3 shadow-lg"%>
      <%= f.label :email, hidden: true %>
      <%= f.email_field :email, 
                        autofocus: true,
                        placeholder: 'email',
                        class: "my-3 shadow-lg"%>
      <%= f.submit "Create Account", class: "bg-blue-300 p-3 w-auto shadow-lg rounded hover:bg-blue-500"%>
    <% end %>
    <%= link_to "Log In", login_path, class: "font-bold text-green-700" %>
    <%= notice%>
  </div>
  <%= image_tag("logo_text.png")%>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.full_name) %>
<div class=" flex w-full flex-col">
  <% if @user.cover_image.attached? %>
    <%= image_tag(@user.cover_image, class: "h-56 object-cover 
                                             object-center
                                             shadow-xl mb-4") %>
  <% end %>
  <div class="w-4/5 mx-auto">
    <%= render 'shared/timeline'%>
  </div>
</div>
<div class="flex px-4 shadow-xl py-4 bg-gray-200">
  <div class="flex-col items-center right-sidebar">
    <%= render 'shared/profile_info'%>
  </div>
</div>