config/routes.rb
Rails.application.routes.draw do
  root                     'recipes#index'
  post   '/',          to: 'recipes#create'  
  # get    '/recipes/search', to: 'recipes#search'
  get    '/sign_up',   to: 'users#new'
  
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  post   '/follows',   to: 'follows#follow_user'
  delete '/follows',   to: 'follows#unfollow_user'

  resources :users
  resources :recipes do
    resource :like, module: :recipes
    member do
      put 'upvote', to: 'recipes#upvote'
      put 'downvote', to: 'recipes#downvote'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if @user.errors.any?%>
  <div id="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |msg|%>
        <li class="text-red-600 font-bold"><%= msg %></li>
        <br>
      <%end%>
    </ul>
  </div>
<%end%>

app/views/shared/_follow_button.html.erb
<button class="px-3 py-2 justify-center rounded bg-blue-500 hover:bg-blue-700 text-white">
  <%= link_to "Follow", follows_path(id: @user.id), method: :post %>
</button>

app/views/shared/_img_upload.html.erb
<%= form_with(model: current_user,
              class: "flex flex-col justify-around") do |f| %>
  <%= f.label :photo, "Choose profile picture", class: "bg-gray-600 justify-center hover:bg-blue-500 flex shadow-md p-3 mb-3 items-center rounded-lg" %>
  <%= f.file_field :photo, hidden: true %>
  <%= f.label :cover_image, "Choose cover image", class: "bg-gray-600 justify-center hover:bg-blue-500 flex shadow-md mb-3 p-3 items-center rounded-lg" %>
  <%= f.file_field :cover_image, hidden: true %>
  <%= f.submit 'Upload', class: "rounded-lg hover:bg-green-400 shadow-lg text-sm p-1"%>
<% end %>

app/views/shared/_left_sidebar.html.erb
<div class="flex flex-col text-gray-700 w-1/6 h-screen sticky top-0 bg-gray-800">
  <div class="user-profile flex-col justify-around flex h-56 bg-gray-900  h-32">
    <div class="avatar text-2xl px-3 py-2 justify-between items-center flex">
      <% if current_user.photo.attached? %>
        <%= image_tag(current_user.photo, class: "w-12 h-12
                                                    rounded-full
                                                    object-cover
                                                    object-center") %>
      <% end %>
      <span class="p-1 text-base font-bold text-gray-600 uppercase text-justify">
        <%= current_user.full_name %>
      </span>
    </div>
    <div class="follows text-sm text-center text-gray-200 flex mt-4 justify-around">
      <p class="m-2 text-xl leading-none font-bold"><%= current_user.follower_count %> <br>
        <span class="font-bold text-base text-gray-600">Followers</span></p>
      <p class="m-2 text-xl leading-none font-bold"><%= current_user.follow_count %> <br>
        <span class="font-bold text-base text-gray-600">Following</span></p>
    </div>
  </div>
  <div class="flex flex-col justify-between">
    <div class="flex flex-col items-center items-start justify-between h-48 font-bold mt-5 uppercase">
      <%= link_to "Home", :root, class: "p-5 hover:text-gray-400" %>
      <%= link_to "Profile", current_user, class: "p-5 hover:text-gray-400" %>
      <%= link_to "Log out", logout_path, method: :delete, class: "p-5 hover:text-gray-400" %>
    </div>
    <%= image_tag('logo.png', class: "w-20 mx-auto")%>
  </div>
</div>

app/views/shared/_new_recipe.html.erb
<%= form_with(model: @recipe, local: true,
                              class: "flex text-center 
                                      text-blue-500 
                                      flex-col m-5
                                      w-5/6 mx-auto
                                      text-2xl
                                      rounded-lg") do |f| %>
  <%= f.label      :title, hidden: true%>
  <%= f.text_field :title, placeholder: 'recipe name',
                           class: "text-center 
                                     bg-gray-300 
                                     rounded mb-3" %>
  <%= f.label     :description, hidden: true %>
  <%= f.text_area :description, placeholder: "Recipe directions",
                                class: "text-center p-10 
                                          bg-gray-300 
                                          rounded mb-3" %>
  <%= f.label      :ingredient_tags, hidden: true%>
  <%= f.text_field :ingredient_tags, placeholder: 'Please write a comma-separated ingredient list here',
                                     class: 'text-center bg-gray-300 rounded mb-3'%>
  <%= f.submit 'Post', class: "py-2 text-center shadow-lg 
                               rounded bg-blue-500 
                               hover:bg-blue-700 text-white" %>
<% end %>

app/views/shared/_profile_info.html.erb
<div class="img-and-name border-b-2 mb-3">
  <% if @user.photo.attached? %>
    <%= image_tag(@user.photo, class: "w-32 object-center object-cover h-32 mx-auto rounded-full") %>
  <% end %>
  <p class="font-bold text-center p-3">
    <%= @user.full_name %> <br>
    <small class="text-gray-700"><%= @user.username %></small>
  </p>
</div>
<div class="info text-center justify-evenly justify-center flex">
  <div class="count-box flex-1 ">
    <p class="p-3 text-gray-700 font-bold">
      <%= @user.post_count %> <br>
      <span class="uppercase text-xs text-gray-400"> Posts</span>
    </p>
  </div>
  <div class="count-box flex-1 ">
    <p class="p-3 text-gray-700 font-bold">
      <%= @user.follow_count %> <br>
      <span class="uppercase text-xs text-gray-400"> Following</span>
    </p>
  </div>
  <div class="count-box flex-1 ">
    <p class="p-3 text-gray-700 font-bold">
      <%= @user.follower_count %> <br>
      <span class="uppercase text-xs text-gray-400"> Followers</span>
    </p>
  </div>
</div>
<div class="button flex justify-center">
  <%= follow_actions(@user) %>
</div>
<%= user_photo_upload(current_user)%>
<%# Follower list %>
<p class="m-2 text-gray-500 underline font-bold text-sm uppercase">Followers</p>
<% @people.each do |person| %>
  <%= link_to user_path(person) do %>
    <div class="person-box hover:shadow-2xl w-full text-gray-700 
                font-bold shadow-lg rounded-lg flex px-10 py-3 my-3 
                h-24  items-center justify-center">
      <div class="img-box w-32">
        <% if person.photo.attached? %>
          <%= image_tag(person.photo, class: "w-16 h-16 rounded-full") %>
        <% end %>
      </div>
      <div class="person-info">
        <p><%= person.full_name %></p>
        <small class="text-gray-500">
          <%= follow_status(person) %>
        </small>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_right_sidebar.html.erb
<%= render @user == current_user ? 'shared/who_to_follow' : 'shared/profile_info' %>

app/views/shared/_search.html.erb
<div class=" border-b-2 w-5/6 border-gray-400 mx-auto border-gray-400">
  <%= search_form_for(@q, class: "flex text-center 
                                      text 
                                      flex-col 
                                      w-full
                                      
                                      text-2xl
                                      ") do |f| %>
    <%= f.label        :ingredients_title_cont, hidden: true %>
    <%= f.search_field :ingredients_title_cont, 
                        placeholder: 'Search recipes by ingredients',
                        class:       'p-3 text-blue-500 text-center
                                      rounded mb-3 bg-gray-300' %>
    <%= f.submit 'Search', class: 'py-1 text-center shadow-lg 
                                   rounded bg-blue-500 
                                   hover:bg-blue-700 text-white' %>
  <% end %>
</div>

app/views/shared/_timeline.html.erb
<% @timeline.each do |recipe| %>
  <%= link_to recipe do %>
    <div class="m-5 shadow-lg text-gray-600 rounded-lg flex-wrap 
              hover:shadow-2xl bg-gray-100 flex p-2">
      <div class="img-and-text w-full flex">
        <div class="img-box w-24 mb-4 h-32">
          <% if recipe.author.photo.attached? %>
            <%= image_tag(recipe.author.photo, 
                        class: "rounded-full
                                mx-auto mb-2 
                                h-20 w-20
                                object-cover
                                object-center")%>
          <% end %>
          <span class="font-bold text-gray-900">
            <%= recipe.author.full_name %>
          </span>
        </div>
        <div class=" p-4 w-11/12 text-justify flex flex-col">
          <h2 class="font-bold text-lg text-center text-gray-900">
            <%= recipe.title %>
          </h2>
          <p class=""><%= recipe.truncated_description%></p>
        </div>
      </div>
      <div class="time-and-tags flex w-full items-end justify-between">
        <small class="text-xs self-end whitespace-no-wrap">
          <span class="flex text-center">
            <span><svg class="w-4 fill-current text-green-400" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Arrow_up" viewBox="0 0 20 20" xml:space="preserve"><path d="M10 2.5L16.5 9H13v8H7V9H3.5L10 2.5z"/></svg>
              <small><%= recipe.get_likes.size %></small></span>
            <span><svg class="w-4 fill-current text-red-400" style="transform: rotate(180deg);" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Arrow_up" viewBox="0 0 20 20" xml:space="preserve"><path d="M10 2.5L16.5 9H13v8H7V9H3.5L10 2.5z"/></svg>
              <small><%= recipe.get_dislikes.size %></small></span>
          </span>
          <%= distance_of_time_in_words_to_now(recipe.created_at) %>
        </small>
        <ul class="flex flex-wrap">
          <% recipe.ingredient_tags.each do |tag|%>
            <li class="m-1 rounded-full  px-3 text-xs bg-gray-300 border-gray-400 border-2"><%= tag %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_unfollow_button.html.erb
<button class="px-3 py-2 justify-center rounded bg-blue-500 hover:bg-blue-700 text-white">
  <%= link_to "Unfollow", follows_path(followed_id: @user.id), method: :delete %>
</button>

app/views/shared/_who_to_follow.html.erb
<h3 class="text-gray-500 border-b-2 mb-10 border-gray-400 uppercase ">
  Who to follow
</h3>
<% @people.each do |person| %>
  <%= link_to user_path(person) do %>
    <div class="person-box w-full text-gray-700 
                font-bold shadow-lg rounded-lg flex px-10 py-3  
                h-24  items-center justify-center hover:shadow-2xl">
      <div class="img-box w-32">
        <% if person.photo.attached? %>
          <%= image_tag(person.photo, class: "w-16 rounded-full") %>
        <% end %>
      </div>
      <div class="person-info">
        <p><%= person.full_name %></p>
        <small class="text-gray-500">
          <%= follow_status(person) %>
        </small>
      </div>
    </div>
  <% end %>
<% end %>